service: bpa

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true
#  include:
#    - ../node_modules

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      packagePath: ./package.json

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: us-west-2
  environment:
    STAGE: ${opt:stage}
    DB_NAME: ${ssm:/bpa/${opt:stage}/postgres/db}
    DB_HOST: ${ssm:/bpa/${opt:stage}/postgres/host}
    DB_USER: ${ssm:/bpa/${opt:stage}/postgres/user}
    DB_PASS: ${ssm:/bpa/${opt:stage}/postgres/pass}
  apiGateway:
    restApiId:
      'Fn::ImportValue': BPAGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': BPAGateway-rootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter*
      Resource: 'arn:aws:ssm:us-west-2:*:parameter/*'
    - Effect: Allow
      Action:
        - cognito-idp:AdminListGroupsForUser
        - cognito-idp:AdminAddUserToGroup
        - cognito-idp:AdminRemoveUserFromGroup
        - cognito-idp:AdminUpdateUserAttributes
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminDisableUser
        - cognito-idp:AdminEnableUser
        - cognito-idp:AdminGetUser
        - cognito-idp:ListUsers
        - cognito-idp:ListGroups
      Resource:
        'Fn::ImportValue': BPAUserPool-arn
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'

functions:
  user:
    handler: endpoints/user/router.main
    description: Endpoints for accessing user data
    events:
      - http:
          path: user
          method: any
          cors: true
          authorizer: aws_iam
      - http:
          path: user/{action}
          method: any
          cors: true
          authorizer: aws_iam
      - http:
          path: user/{action}/{id}
          method: any
          cors: true
          authorizer: aws_iam
